import { Lead } from "@/types";

export const MOCK_LEADS: Lead[] = [
    {
        id: '1',
        companyName: 'TechFlow Systems',
        contactName: 'Sarah Chen',
        email: 'sarah@techflow.com',
        phone: '+1 (555) 123-4567',
        value: 12500,
        status: 'Negotiation',
        probability: 75,
        lastContact: Date.now() - 86400000 * 2,
        nextStep: 'Contract Review',
        assignedTo: 'user1',
        industry: 'SaaS',
        createdAt: Date.now(),
        updatedAt: Date.now()
    },
    {
        id: '2',
        companyName: 'Global Manufacturing',
        contactName: 'Mike Ross',
        email: 'mike@globalmfg.com',
        phone: '+1 (555) 234-5678',
        value: 45000,
        status: 'Qualified',
        probability: 40,
        lastContact: Date.now() - 86400000 * 5,
        nextStep: 'Schedule Demo',
        assignedTo: 'user1',
        industry: 'Manufacturing',
        createdAt: Date.now(),
        updatedAt: Date.now()
    },
    {
        id: '3',
        companyName: 'Beacon Healthcare',
        contactName: 'Dr. James Wilson',
        email: 'jwilson@beacon.org',
        phone: '+1 (555) 345-6789',
        value: 28000,
        status: 'Proposal',
        probability: 60,
        lastContact: Date.now() - 86400000,
        nextStep: 'Stakeholder Meeting',
        assignedTo: 'user1',
        industry: 'Healthcare',
        createdAt: Date.now(),
        updatedAt: Date.now()
    },
    {
        id: '4',
        companyName: 'Apex Logistics',
        contactName: 'Robert Martinez',
        email: 'robert@apex.com',
        phone: '+1 (555) 456-7890',
        value: 18500,
        status: 'Contacted',
        probability: 20,
        lastContact: Date.now() - 86400000 * 3,
        nextStep: 'Discovery Call',
        assignedTo: 'user1',
        industry: 'Logistics',
        createdAt: Date.now(),
        updatedAt: Date.now()
    },
    {
        id: '5',
        companyName: 'Quantum FinServ',
        contactName: 'Jessica Pearson',
        email: 'jessica@quantum.com',
        phone: '+1 (555) 567-8901',
        value: 95000,
        status: 'New',
        probability: 10,
        lastContact: Date.now() - 86400000 * 10,
        nextStep: 'Initial Outreach',
        assignedTo: 'user1',
        industry: 'Finance',
        createdAt: Date.now(),
        updatedAt: Date.now()
    },
    {
        id: '6',
        companyName: 'CyberShield Security',
        contactName: 'David Kim',
        email: 'david@cybershield.io',
        phone: '+1 (555) 678-9012',
        value: 32000,
        status: 'Qualified',
        probability: 45,
        lastContact: Date.now() - 86400000 * 4,
        nextStep: 'Technical Validation',
        assignedTo: 'user1',
        industry: 'Cybersecurity',
        createdAt: Date.now(),
        updatedAt: Date.now()
    }
];
